### ISSUE TITLE
Annotation error : @http in method Aws\AwsClientInterface::getCommand()

### ISSUE THREAD

**Issue by GCalmels** [1up-lab/OneupFlysystemBundle#121]
Hey,

I have this error :
The annotation "@http" in method Aws\AwsClientInterface::getCommand() was never imported.
when I try to use S3.
Symfony thinks that "@http" is an annotation, is it possible to do otherwise?
I tried aws-sdk-php-symfony without any more success

Thanks

**Comment by bytehead** [comment]
That's actually an issue of [aws-sdk-php](https://github.com/aws/aws-sdk-php/blob/master/src/AwsClientInterface.php#L32).  
There's also a question (& answer) on stackoverflow: http://stackoverflow.com/questions/36479101/symfony-3-with-aws-client-throws-annotationexception-http-annotation

I close this, because it's a issue in the `aws-sdk-php` library.

**Comment by GCalmels** [comment]
Hey, I have already post an issue on aws-sdk-php : https://github.com/aws/aws-sdk-php/issues/1134 without any success!
And the answer on StackOverflow does not work for me...

For now, I solve the problem in autoload file with `AnnotationReader::addGlobalIgnoredName('http');`

**Comment by bytehead** [comment]
Ok, maybe we could integrate this somehow in our `AwsS3V*Factory` class?
