### ISSUE TITLE
Features request: download helper and zip generation helper

### ISSUE THREAD

**Issue by fabienlem** [1up-lab/OneupFlysystemBundle#186]
Hello!

I would like to suggest features addition on this bundle.

**Download helper**

The first one is to provide an helper that allow file download. It's something not really straight forward and I had trouble finding out how to do it.

The Vich Uploader bundle provide a such feature [see: createDownloadResponse()](https://github.com/dustin10/VichUploaderBundle/blob/master/Handler/DownloadHandler.php#L62).

**Zip generation helper**

The second one is to add a shortcut that allow zip generation. I think it would be nice to provide a way to generate one-shot zip archives, ie: without any yaml configuration. 

Possible use-cases:
- generate a zip archive on exportation purpose
- generate a zip archive on another flysystem

I found [this code sample](https://github.com/thephpleague/flysystem/issues/28#issuecomment-29643002) that could be reworked on this purpose.

Thank you for reading and for your feedback!

Fabien

**Comment by bytehead** [comment]
Hello

Thanks for your contribution!

It's not this bundle's responsibility to provide a download helper nor a zip generation helper. This bundle just glues the flysystem php library into the symfony (bundle) ecosystem.

But as stated in the mentioned code example, it's pretty easy to implement this kind of logic yourself.

I'll close this because it's out of this bundle's scope.
