### ISSUE TITLE
[Question] Difference to thephpleague/flysystem-bundle

### ISSUE THREAD

**Issue by michaelKaefer** [1up-lab/OneupFlysystemBundle#205]
Could someone explain to me why there are two bundles for the same cause? What is the difference to thephpleague/flysystem-bundle? Which one should we use? Sorry for posting it as an issue but I don't know where else I could ask.

**Comment by bytehead** [comment]
See https://github.com/1up-lab/OneupFlysystemBundle/pull/190 and the discussion on twitter https://twitter.com/Majkl578/status/1119272779856195584. It's up to you which to use, can't give you an unbiased opinion here 😉

**Comment by michaelKaefer** [comment]
To sum it up it up for further readers who have the same question: `1up-lab/OneupFlysystemBundle` was released 2017 and has about 5,100,000 downloads on packagist in January 2020. Without any reason another bundel was released in 2019, named `thephpleague/flysystem-bundle` with 200,000 downloads. On Twitter (see the link in the comment above) one of the creators of the new bundle did not answer the question on why the new bundle was built. But he claims that it is the official bundle [here](https://titouangalopin.com/introducing-the-official-flysystem-bundle/) and Flysystem claims the same [here](https://flysystem.thephpleague.com/v1/docs/guides/symfony-usage/). But Symfony does nowhere say which one is official as far as I found out and in Symfonycasts they use `1up-lab/OneupFlysystemBundle`. So in short: **it seems that there is no good reason why `thephpleague/flysystem-bundle` even exists** or there is but the authors do not want to tell us. That is why I will use `1up-lab/OneupFlysystemBundle`.

**Comment by michaelKaefer** [comment]
I asked the same question on the other side: https://github.com/thephpleague/flysystem-bundle/issues/37

**Comment by tgalopin** [comment]
Hello,

Please feel free to use the OneUpFlysystemBundle. It's a great bundle.

Official in my article means I have discussed it with the author of Flysystem in order to create a better integration between Flysystem and Symfony than what was possible before. It is official as it is under the PHPLeague umbrella, not from Symfony POV.

Note: I tend to dislike the tone and lack of question of your message. It does not invite to discuss in a sensible way about technology and instead rely on preconceived ideas you have. I'll continue working on trying to improve the open-source Symfony ecosystem and I usually ignore such messages. If you have question, feel free to reach me.

**Comment by michaelKaefer** [comment]
I am sorry for my tone, maybe it was to rude. And thank you for the clearification.
